#!/system/bin/sh
log_dir=/data/misc/logging/
device=mt8163-generic
d=$(date +%Y-%m-%d)
LOG=/data/misc/logging/amz
command="$1"
function -h {
echo " -i  start the logging for init"
echo " -tb take a bug report and send it to the sd card"
echo " -h  Show Help Documentation"
echo " -e  export the bugreport data to /sdcard to the zip file"
echo " -p  take the hardware info and debug report"
}

function -i {
mkdir -p $log_dir
rm -rf $LOG
mkdir -p $LOG
}

function -p {
cat /proc/last_kmsg >$LOG/SYSTEM_LAST_KMSG
cat /proc/life_cycle_reason >$LOG/BOOT_REASON
idme print > $LOG/IDME
}

function -tb {
-i
mdkir -p /sdcard/tmp
bugreport > /sdcard/tmp/bugreport-$device-$d.log
timeout 10 logcat > /sdcard/tmp/logcat.log
getprop > /sdcard/tmp/properties.prop
-p
cp -r $LOG /sdcard/tmp/
tar -zcf bugreport-$device-$d.tar.gz /sdcard//tmp
mv /sdcard/tmp/bugreport-$device-$d.tar.gz /sdcard/
cleanup
}

function cleanup {
rm -rf /data/misc/logging/amz
rm -rf /sdcard/tmp/
}

$command
