#!/system/bin/sh
# Copyright (C) 2019 Kai Jones
# /vendor/bin/debug_tool
# This program is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the License, 
# or (at your option) any later version.This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.You should have 
# received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
log_dir=/data/misc/logging/
device=mt8163-generic
d=$(date +%Y-%m-%d)
LOG=/data/misc/logging/amz
command="$1"
# increase printk verbosity in dmesg
echo 8 > /proc/sys/kernel/printk

function cleanup {
rm -rf /data/misc/logging/amz
rm -rf /sdcard/tmp/
}

function -h {
echo " -i  prepare folders for taking bug report"
echo " -tb take a bug report and send it to the sd card"
echo " -h  Show Help Documentation"
echo " -p  take the hardware info and debug report"
}

function -i {
mkdir -p $log_dir
rm -rf $LOG
mkdir -p $LOG
}

function -p {
cat /proc/last_kmsg >$LOG/SYSTEM_LAST_KMSG
cat /proc/life_cycle_reason >$LOG/BOOT_REASON
idme print > $LOG/IDME
}

function -tb {
-i
mkdir -p /sdcard/tmp
#bugreport > /sdcard/tmp/bugreport-$device-$d.log disabled because this is causing issues with the device
timeout 10 logcat > /sdcard/tmp/logcat.log
getprop > /sdcard/tmp/properties.prop
-p
cp -r $LOG /sdcard/tmp/
tar -zcf bugreport-$device-$d.tar.gz /sdcard/tmp
mv /sdcard/tmp/bugreport-$device-$d.tar.gz /sdcard/
cleanup
}

$command
