
/* Set Config Handle */
OMX_ERRORTYPE HandleSetConfigVideoFramerate(OMX_CONFIG_FRAMERATETYPE*);
OMX_ERRORTYPE HandleSetConfigVideoBitrate(OMX_VIDEO_CONFIG_BITRATETYPE*);
OMX_ERRORTYPE HandleSetConfigVideoIntraVOPRefresh(OMX_CONFIG_INTRAREFRESHVOPTYPE*);
OMX_ERRORTYPE HandleSetConfigVideoAVCIntraPeriod(OMX_VIDEO_CONFIG_AVCINTRAPERIOD*);

OMX_ERRORTYPE HandleSetConfigVendorSetForceIframe(OMX_PARAM_U32TYPE*);
OMX_ERRORTYPE HandleSetConfigVendorSetIInterval(OMX_PARAM_U32TYPE*);
OMX_ERRORTYPE HandleSetConfigVendorSetForceFullIframe(OMX_PARAM_U32TYPE*);

OMX_ERRORTYPE HandleSetConfigVendorSkipFrame(OMX_PARAM_U32TYPE*);
OMX_ERRORTYPE HandleSetConfigVendorDrawBlack(OMX_PARAM_U32TYPE*);

OMX_ERRORTYPE HandleSetConfigVendorSliceLossIndication(OMX_CONFIG_SLICE_LOSS_INDICATION*);
OMX_ERRORTYPE HandleSetConfigVendorResolutionChange(OMX_VIDEO_PARAM_RESOLUTION*);
OMX_ERRORTYPE HandleSetConfigVendorInputScaling(OMX_CONFIG_BOOLEANTYPE*);
OMX_ERRORTYPE HandleSetConfigVendorConfigQP(OMX_VIDEO_CONFIG_QP*);

OMX_ERRORTYPE HandleSetConfigOperatingRate(OMX_PARAM_U32TYPE*);

OMX_ERRORTYPE HandleSetConfigGoogleIntraRefresh(OMX_VIDEO_CONFIG_ANDROID_INTRAREFRESHTYPE*);
OMX_ERRORTYPE HandleSetConfigGoogleTemporalLayering(OMX_VIDEO_CONFIG_ANDROID_TEMPORALLAYERINGTYPE*);

/* Get Config Handle */
OMX_ERRORTYPE HandleGetConfigVideoFramerate(OMX_CONFIG_FRAMERATETYPE*);
OMX_ERRORTYPE HandleGetConfigVideoBitrate(OMX_VIDEO_CONFIG_BITRATETYPE*);
OMX_ERRORTYPE HandleGetConfigVideoIntraVOPRefresh(OMX_CONFIG_INTRAREFRESHVOPTYPE*);
OMX_ERRORTYPE HandleGetConfigVideoAVCIntraPeriod(OMX_VIDEO_CONFIG_AVCINTRAPERIOD*);
OMX_ERRORTYPE HandleGetConfigGoogleIntraRefresh(OMX_VIDEO_CONFIG_ANDROID_INTRAREFRESHTYPE*);
OMX_ERRORTYPE HandleGetConfigGoogleTemporalLayering(OMX_VIDEO_CONFIG_ANDROID_TEMPORALLAYERINGTYPE*);
